name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Étape 3 : Déployer le code
      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

      # Étape 4 : Nettoyer les clés SSH
      - name: Clean up
        run: |
          rm -rf ~/.ssh

# ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
