name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js et dépendances pour exécuter les tests React
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install

      - name: Run React tests
        run: |
          npm test -- --ci --reporters=default --reporters=jest-junit

      # Étape 3 : Configurer la connexion SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # Étape 4 : Déployer le code et gérer les conteneurs Docker
      - name: Deploy to EC2 with Docker
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            cd ${{ secrets.WORK_DIR }}
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull
            docker-compose -f docker-compose.yml down
            docker system prune -af
            docker image prune -af
            docker-compose up -d --build
          EOF

      # Étape 5 : Nettoyer les clés SSH
      - name: Clean up
        run: |
          rm -rf ~/.ssh
