name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer SSH
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Ajout de l'hôte à la liste known_hosts
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      # Étape 3 : Déployer le code
      - name: Deploy to EC2
        run: |
          ssh serverweb@$35.180.225.154 "cd /home/serverweb/site/react-github-aws && git checkout main && git pull"

      # Étape 4 : Nettoyer les clés SSH
      - name: Clean up
        run: |
          rm -rf ~/.ssh
